cart/urls.py
from django.urls import path
from .views import CartAdd,CartRemove,cart_detail

app_name='cart'
urlpatterns=[
    path('',cart_detail,name='cart_detail'),
    path('add/<int:product_id>',CartAdd.as_view(),name='cart_add'),
    path('remove/<int:product_id>',CartRemove.as_view(),name='cart_remove')
]

myshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('accounts/', include('allauth.urls')),
    path("djangorave/", include("djangorave.urls", namespace="djangorave")),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddProducts(forms.Form):
    quantity =forms.IntegerField()
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from .forms import CartAddProducts
from shop.models import Product
from django.views import View


class CartAdd(View):
    def post(self,request,product_id,*args,**kwargs):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        form = CartAddProducts(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,quantity=cd['quantity'],override_quantity=True)

        return redirect('cart:cart_detail')


class CartRemove(View):
    def post(self,request,product_id,*args,**kwargs):
        cart = Cart(request)
        product = get_object_or_404(Product,id=product_id)
        cart.remove(product)

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProducts(initial={
                                                    'quantity':item['quantity'],
                                                    'override':True})
    return render(request,'cart/detail.html',{'cart':cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}

  <!-- Cart Items -->
  <div class="container-md cart">
    <table>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Subtotal</th>
      </tr>

        {% for item in cart %}
        {% with product=item.product %}
        <tr>
        <td>
          <div class="cart-info">
            <a href="{{product.get_absolute_url}}">
            <img src="{{product.product_image}}" alt="">
            </a>
            <div>
              <p><a href="{% url 'product_detail' product.pk%}" style="color:black;">{{product.product_name}}</a></p>
              <span>{{produce.product_price}}</span>
              <br />
              <form class="" action="{% url 'cart:cart_remove' product.id%}" method="POST">
                {% csrf_token %}
                <a href="{% url 'cart:cart_remove' product.id%}"><input style="border:0;background:0;color:red;" value="remove" type="submit"></a>
              </form>
            </div>
          </div>
        </td>

        <!-- htmx later -->
        <td>{{item.quantity}}
          <form action="{% url 'cart:cart_add' product.id %}" method="POST">
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.override }}
            <input style="border:0;background:0;color:green;" type="submit" value="update">
            {% csrf_token %}
          </form>
        </td>


        <td>&#x20A6;{{item.total_price}}</td>
        </tr>
        {% endwith %}
        {% endfor %}

    </table>

    <div class="total-price">
      <table>
        <tr>
          <td>Subtotal</td>
          <td>&#x20A6;{{item.total_price}}</td>
        </tr>
        <tr>
          <td>Delivery</td>
          <td>&#x20A6;50</td>
        </tr>
        <tr>
          <td>Total</td>
          <td>&#x20A6;{{cart.get_total_price}}</td>
        </tr>
      </table>
      <a href="#" class="checkout btn">Proceed To Checkout</a>
      <a href="{% url 'product_list'%}" class="checkout btn">Continue Shopping</a>



    </div>

  </div>


{% endblock content %}